/* DO NOT EDIT THIS FILE - it is machine generated */
#include "D:\Project\Java\Test_project\src\test_project\jni.h"
/* Header for class test_project_Test_nativeMethod */

#ifndef _Included_test_project_Test_nativeMethod
#define _Included_test_project_Test_nativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_project_Test_nativeMethod
 * Method:    helloworld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_1project_Test_1nativeMethod_helloworld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
